### ISSUE TITLE
BMI2 fails to compile with gcc 9.3.0 and 7.3.0 "_tzcnt_u64 inlining failed"

### ISSUE THREAD

**Issue by maxrossi91** [xxsds/sdsl-lite#97]
I am trying to compile sdsl with GCC 9.3.0 and 7.3.0 and I get the following error:

```
In file included from /.../lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/immintrin.h:103,
                 from /.../lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/x86intrin.h:32,
                 from /.../projects/sdsl-lite/test/../include/sdsl/bits.hpp:18,
                 from /.../projects/sdsl-lite/test/../include/sdsl/int_vector.hpp:30,
                 from /.../projects/sdsl-lite/test/../include/sdsl/construct_bwt.hpp:16,
                 from /.../projects/sdsl-lite/test/../include/sdsl/construct.hpp:14,
                 from /.../projects/sdsl-lite/test/../include/sdsl/wavelet_trees.hpp:19,
                 from /.../projects/sdsl-lite/test/wt_int_test.cpp:7:
/.../lib/gcc/x86_64-pc-linux-gnu/9.3.0/include/bmiintrin.h:172:1: error: inlining failed in call to always_inline ‘long long unsigned int _tzcnt_u64(long long unsigned int)’: target specific option mismatch
  172 | _tzcnt_u64 (unsigned long long __X)
      | ^~~~~~~~~~
In file included from /.../projects/sdsl-lite/test/../include/sdsl/int_vector.hpp:30,
                 from /.../projects/sdsl-lite/test/../include/sdsl/construct_bwt.hpp:16,
                 from /.../projects/sdsl-lite/test/../include/sdsl/construct.hpp:14,
                 from /.../projects/sdsl-lite/test/../include/sdsl/wavelet_trees.hpp:19,
                 from /.../projects/sdsl-lite/test/wt_int_test.cpp:7:
/.../projects/sdsl-lite/test/../include/sdsl/bits.hpp:588:22: note: called from here
  588 |     return _tzcnt_u64(_pdep_u64(1ULL << (i - 1), x));
      |            ~~~~~~~~~~^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
```

**Comment by eseiler** [comment]
Thanks for reporting.

`_tzcnt_u64` requires `-mbmi`, which is not set by `-mbmi2`.

#98 adds the check. You may need to run CMake from scratch for the changes to apply.

**Comment by maxrossi91** [comment]
Thank this solves the issue.
